# Topics
camera_topic: "/image"
camera_info: "/sekonix_camera/port_a_cam_0/camera_info"
lidar_topic: "/os_cloud_node/points"

# Dynamic rqt_reconfigure default bounds
feature_extraction:
  x_min: 3.0
  x_max: 10.0
  y_min: -4.0
  y_max: 4.0
  z_min: -5.0
  z_max: 0.0
  k: 50
  z: 1
  voxel_res: 0.4
  
# Properties of chessboard calibration target
chessboard:
  pattern_size:
    height: 7
    width: 5  
  square_length: 95
  board_dimension:
    width: 610
    height: 850
  translation_error:
    x: 2
    y: 0
